### ISSUE TITLE
Add objects 'Construction' with the same name

### ISSUE THREAD

**Issue by JorisM83320** [openergy/oplus#13]
`roof = idf.add_object(IDD[idd_version]['Construction'])
roof['Name'] = 'type roof 1'
roof.add_field(roof_mat)

floor = idf.add_object(IDD[idd_version]['Construction'])
floor['Name'] = 'type floor 1'
floor.add_field(floor_mat)`

No error is raised when declaring two different constructions with the same name

**Comment by Lefort-Antoine** [comment]
Issue's information are not clear enough. 

`
idf = op.Idf("")

idf.add("""Construction,
        construction_ref_1;""")

idf.add("""Construction,
        construction_ref_1;""")`

Error is raised. (oplus version 6.1.1)

> BrokenIdfError: Reference duplicate for link name: ConstructionNames
Reference: construction_ref_1
Detected while checking record ref: Construction
Field: 0
