### ISSUE TITLE
add_field >101 for IDD list description error

### ISSUE THREAD

**Issue by Lefort-Antoine** [openergy/oplus#15]
Due to error in .idd description object (BranchList, NodeList, ..) 
Add optional argument : ' byref=False'  in add_field() function (idf.py)

**Comment by abydash** [comment]
![image](https://cloud.githubusercontent.com/assets/17151533/21947667/4f020cae-d9b4-11e6-87d4-274d95f526f9.png)

I still get the error after adding the optional argument

**Comment by Lefort-Antoine** [comment]
the synthaxe to add field to an object is object.add_field(value)
`import oplus as op
# create an empty idf
idf = op.Idf(""" """)`
# add an buildingsurface object
bsd_o = idf.add("""BuildingSurface:Detailed,
   surface_example,          ! - Name
    floor,                           ! - Surface Type
    ,                                  ! - Construction Name
    ,                                  ! - Zone Name
    zone,                          ! - Outside Boundary Condition
    ,                                  ! - Outside Boundary Condition Object
    nosun,                        ! - Sun Exposure
    nowind,                      ! - Wind Exposure
    ,                                  ! - View Factor to Ground
    2,                                ! - Number of Vertices
    -18.436949171,
    21.6350748574,
    11.4;""")
# you can also get it with
bsd_o = idf["BuildingSurface:Detailed"].one()
# or 
bsd_o = idf["BuildingSurface:Detailed"].one(lambda  x: x['Name'] == "surface_example")
bsd_o.add_field(2)
'
