### ISSUE TITLE
'set_start' command does'nt work

### ISSUE THREAD

**Issue by thomascerbelaud** [openergy/oplus#2]
file : eso.py

When creating a dataframe from a .eso file, the start year cannot be previously set using the 'set_start' command : (s being defined as s = simulate(idf, epw_path, dir_path))

---

s.eso.set_start(2004)
s.eso.df(datetime_index=True,)

---

**Comment by Lefort-Antoine** [comment]
New command is:

```
eso = s.get_out_eso()
eso.create_datetime_index(2004)
df = eso.get_data()
```

It have been tested.
