### ISSUE TITLE
parse IDD 9.2.0

### ISSUE THREAD

**Issue by Lefort-Antoine** [openergy/oplus#26]
There is an error parsing idd 9.2.0.

> File "D:\Code\Bibliotheque\develop\oplus\tests\test_idd.py", line 11, in test_load
    idd = Idd()
  File "D:\Code\Bibliotheque\develop\oplus\oplus\idd\idd.py", line 52, in __init__
    self._parse(f)
  File "D:\Code\Bibliotheque\develop\oplus\oplus\idd\idd.py", line 171, in _parse
    raise RuntimeError("Line %i not parsed: '%s'." % (i+1, raw_line))
RuntimeError: Line 18629 not parsed: '  A42,A43,N21,A44,A45,N22,A46,A47,N23,A48,A49,N24,A50,A51,N25,A52,A53,N26,A54,A55,N27,A56,A57,N28,A58,A59,N29,A60,A61,N30,
'.

**Comment by geoffroy-destaintot** [comment]
done
