### ISSUE TITLE
Open Eplaunch simulation

### ISSUE THREAD

**Issue by Lefort-Antoine** [openergy/oplus#28]
Impossible to open a Eplaunch simulation.
` simulation = op.Simulation(EPLAUNCH_DIR_PATH)`

> WARNING:oplus.simulation:Info file not found (info.json), we will creating one. This can happen if simulation was probably not created by oplus.
Traceback (most recent call last):
  File "D:/Code/Bibliotheque/develop/obat/samples/v00_run.py", line 1237, in <module>
    s = op.Simulation(r"C:\Users\l3f0r\Desktop\eplus_test\baseboard_crash")
  File "D:\Code\Bibliotheque\develop\oplus\oplus\simulation.py", line 204, in __init__
    "\n - ".join(lookup_paths)
RuntimeError: idf file not found, can't create simulation object. Looked up paths:
C:\Users\l3f0r\Desktop\eplus_test\baseboard_crash\eplusout.idf
 C:\Users\l3f0r\Desktop\eplus_test\baseboard_crash\oplus.idf
 C:\Users\l3f0r\Desktop\eplus_test\baseboard_crash\Output\oplus.idf

**Comment by geoffroy-destaintot** [comment]
can your give me your EPLAUNCH_DIR_PATH directory so I can have a look ?

**Comment by geoffroy-destaintot** [comment]
ok managed
work must still be done to improve files structure and naming that depend on eplus version and os
