### ISSUE TITLE
Float to Int

### ISSUE THREAD

**Issue by Lefort-Antoine** [openergy/oplus#29]
> ValueError: invalid literal for int() with base 10: '1.0000'

`import` oplus as op
from oplus import CONF
CONF.default_idd_version = (8, 1, 0)

text_file` = open("zone_multiplier_error.idf", "w")
text_file.write("""Zone,
    Perimeter_mid_ZN_4,      !- Name
    0.0000,                  !- Direction of Relative North {deg}
    0.0000,                  !- X Origin {m}
    0.0000,                  !- Y Origin {m}
    0.0000,                  !- Z Origin {m}
    1,                       !- Type
    1.0000,                  !- Multiplier
    2.7432,                  !- Ceiling Height {m}
    autocalculate,           !- Volume {m3}
    autocalculate,           !- Floor Area {m2}
    ,                        !- Zone Inside Convection Algorithm
    ,                        !- Zone Outside Convection Algorithm
    YES;                     !- Part of Total Floor Area""")
text_file.close()

epm = op.Epm.load("zone_multiplier_error.idf", check_required=False)`

**Comment by geoffroy-destaintot** [comment]
ok problem corrected (he couldn't pars '1.000' to int, now he can)
