### ISSUE TITLE
EIO : How can I get every table_refs contained in my oplus.eio file ?

### ISSUE THREAD

**Issue by thomascerbelaud** [openergy/oplus#6]

**Comment by Lefort-Antoine** [comment]
Use  eio._tables_d

**Comment by geoffroy-destaintot** [comment]
maybe we add a public property of this variable ?

**Comment by Lefort-Antoine** [comment]
It has been done.
The command is:
`eio.get_table_refs()`
To get specific table_ref data you have:
`eio..get_df("TABLE REF")`
