### ISSUE TITLE
Filter bug

### ISSUE THREAD

**Issue by geoffroy-destaintot** [openergy/oplus#9]
building = idf("Building").filter(0, "Bldg").one : fails

**Comment by Lefort-Antoine** [comment]
New synthaxe is : 
`epm.Building.one("Bldg")`
Have you fix it ? 
I'm using today:
`epm.Building.one(lambda x: x.name == "Bldg")`

**Comment by geoffroy-destaintot** [comment]
import oplus as op
epm = op.Epm.load(r"C:\EnergyPlusV9-2-0\ExampleFiles\1ZoneUncontrolled.idf")

# syntax one("id") only works for tables who have a primary key
# to have a primary key, the first variable of a table must fulfill both following conditions (see idd):
#  1. must be a reference (\reference)
#  2. must be required (\required-field)


# a building does not have a primary key (none of previous conditions are fulfilled)
# => we use function syntax (both following queries work)
building = epm.Building.one(lambda x: x.name == "Simple One Zone (Wireframe DXF)")
print(building.name)

building = epm.Building.one(lambda x: x[0] == "Simple One Zone (Wireframe DXF)")
print(building.name)

# but a zone does have a primary key
# => we use id syntax or function syntax (the three following queries work)
zone = epm.Zone.one("zone one")
print(zone.name)

zone = epm.Zone.one(lambda x: x.name == "zone one")
print(zone.name)

zone = epm.Zone.one(lambda x: x[0] == "zone one")
print(zone.name)
